# site settings
title: Harvard 
subtitle: AMR Network
year: 2019
email: harvardAMR@gmail.com
description: A Harvard University student group
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
street_address: 665 Huntington Ave
city: Boston
state: MA
zip_code: '02115'
country: United States of America

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
